services:
  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://root:password@db:3306/db
      - WATCHPACK_POLLING=true
    networks:
      - app_network
    depends_on:
      - db

  # Database
  db:
    image: mysql:latest
    volumes:
      - db:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'db'
      MYSQL_PASSWORD: 'password'
    networks:
      - app_network

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 'password'
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db:
  frontend:
  backend:
